### PR TITLE
[Reviewer: Steve] Change command to always work in management namespace.

### PR DESCRIPTION
**Pull request by Tom-Rees**
Fix for [s484279](http://sfr/prodAsp/scripts/MSG/SFR.asp?sfr=484279).

So far only do_backup.sh fix implemented to get feedback early as changes to other scripts will likely be the same.

Testing performed on V7 box both on single and multiple (2 and 3) namespaces.

### CODE REVIEW

**Comment by Tom-Rees** [comment]
Hi Steve,

Please could you review these changes?

As it's bash, feel free to be super picky with the comments / code standard things to give our future selves a chance.

Cheers!
Tom

**Comment by steelyvoid** [comment]
I'm concerned about the basic premise here (that we should be detecting the signaling namespace by seeing whether there's one namespace and using it if so, otherwise asking the operator to choose).  What if customers are doing debian based installs on a system that has a single network, but on which they happen to have created a separate namespace for some other reason?

Can you not just do a ". /etc/clearwater/config" and read the $signaling_namespace env var from that?  Note that other scripts in the same directory in clearwater-cassandra use clearwater config (see e.g. poll_cassandra.sh) so there would seem to be a precedent.

**Comment by Tom-Rees** [comment]
Yes, that makes the code simpler. Unfortunately, this is another case where our 'unique' config file rears it's ugly head:
```bash
if [ "$(ip netns list)" = "signalling" ]; then
   signaling_namespace=signalling
   signaling_dns_server=$(grep "^[[:space:]]*nameserver" /etc/netns/signalling/resolv.conf | awk '{print $2}'|sed -e :a -e N -e 's/\n/,/' -e ta)
   [ -z "$signaling_namespace" ] ||
   namespace_prefix="ip netns exec $signaling_namespace"
else
   namespace_prefix=
   signaling_dns_server=$(grep "^[[:space:]]*nameserver" /run/dnsmasq/resolv.conf | awk '{print $2}'|sed -e :a -e N -e 's/\n/,/' -e ta)
fi
```

Which does an even worse job of determining the correct namespace. 

I think the change is still worthwhile though and we can add this to the ever growing list of reasons why we dislike this config. Once the config file is fixed, this becomes an elegant solution :)

**Comment by rkd-msw** [comment]
FTR, we implemented https://github.com/Metaswitch/clearwater-infrastructure/blob/master/clearwater-infrastructure/usr/share/clearwater/bin/run-in-signaling-namespace to get a consistent implementation of `". /etc/clearwater/config" and read the $signaling_namespace env var`. Worth backporting that script to V7?

**Comment by steelyvoid** [comment]
Thanks for the suggestion, Rob.  

Tom, I think its up to you whether you want to take this as part of this fix, given that its only a 3 line fix anyway

**Comment by Tom-Rees** [comment]
I think I'd rather leave it until we've cleaned up out config file. Adding another layer of abstraction over the config file is likely to make it even harder to work out what values we're using, especially since that file also defines 'namespace_prefix'.

**Comment by Tom-Rees** [comment]
The other scripts already work in the management namespace which is compliant with [the MOP](https://communities.metaswitch.com/docs/DOC-202319#)

**Pull request merged**
